### PR TITLE
Schemas with no unique key, but valid postgres schemas fail

### LINKED ISSUE #5: Schemas with no unique key, but valid postgres schemas fail
a schema like the following should work:

```json
{
    "schemaName": "test01",
    "fields": [
        {
            "fieldName": "Crop",
            "type": "VARCHAR",
            "description": "",
            "maxLength": "",
            "nullable": false,
            "unique": false,
            "vectorEmbed": false
        }
    ],
    "description": "Schema for seed treating materials data with details of each order"
}
 ```

### PR DESCRIPTION
**Pull request by Himasnhu-AT**
Fixes #5

### CODE REVIEW

**Comment by sooraj1002** [comment]
@Himasnhu-AT the schema which was originally mentioned in the issue is still failing with this PR

image

**Comment by sooraj1002** [comment]
it doesnt work with `unique=true` as well 
image

**Comment by Himasnhu-AT** [comment]
that's wired, can you share this json, it's working locally on my system.
Screenshot 2024-04-14 at 5 50 04 PM
Screenshot 2024-04-14 at 5 50 08 PM

**Comment by sooraj1002** [comment]
```json
    {
      schemaName: "test01",
      fields: [
        {
          fieldName: "name",
          type: "VARCHAR",
          description: "",
          maxLength: "",
          nullable: false,
          unique: false,
          vectorEmbed: false,
          isId: true,
        },
      ],
      description:
        "Schema for seed treating materials data with details of each order",
    }
```

**Comment by sooraj1002** [comment]
after adding `isId` to the schema as well, it is failing

```json
const jsonData = {
  schema: [
    {
      schemaName: "test01",
      fields: [
        {
          fieldName: "Crop",
          type: "VARCHAR",
          description: "",
          maxLength: "",
          nullable: false,
          unique: false,
          vectorEmbed: false,
          isId: true,
        },
      ],
      description:
        "Schema for seed treating materials data with details of each order",
    },
  ],
};
```

**Comment by Himasnhu-AT** [comment]
the error seemed to be with the json itself:

Correct Json File: 

```json
{
  "schema": [
    {
      "schemaName": "test01",
      "fields": [
        {
          "fieldName": "Crop",
          "type": "VARCHAR",
          "description": "",
          "maxLength": "",
          "nullable": false,
          "unique": false,
          "vectorEmbed": false
        }
      ],
      "description": "Schema for seed treating materials data with details of each order"
    }
  ]
}
```

Also the type are of form: 

```
[
  'String',      'Int',
  'Float',       'Boolean',
  'DateTime',    'Decimal',
  'Json',        'Bytes',
  'Unsupported'
]
// and enums defined in schema
```

**Comment by sooraj1002** [comment]
@Himasnhu-AT i had only added the actual schema, not the entire data. also, even after making the change for `"String"`, the package is still throwing error 
image

**Comment by Himasnhu-AT** [comment]
its error while validating schema
So, atleast one id should be present or unique value.

**Comment by sooraj1002** [comment]
That's the error we had to solve in the first place.

**Comment by Himasnhu-AT** [comment]
yup, the function return false though it still continues :

```ts
function ensureEachModelHasPrimaryKey(jsonData: Schema): boolean {
  console.log(jsonData.schema);
  jsonData.schema.length > 0
    ? jsonData.schema.forEach((model) => {
        console.warn("Model: ", model);
        const primaryKeyFields = model.fields.filter(
          (field) => field.isId || field.unique
        );
        if (primaryKeyFields.length === 0) {
          console.error(
            `Model ${model.schemaName} does not have a primary key`
          );
          return false;
          process.exit(1);
        }
      })
    : console.log("Wrong format, ", typeof jsonData);
  return true;
}
```

**Comment by Himasnhu-AT** [comment]
Not sure why, but even after throwing error, it continues to run:  

```ts
 if (!ensureEachModelHasPrimaryKey(jsonData)) {
    console.warn("No primary key");
    throw new Error("No primary key");
  }
```

**Comment by techsavvyash** [comment]
https://github.com/techsavvyash/dynamo-prisma/pull/27 solves for this hence closing it out, thanks fo

**Pull request closed without merging**
